// AUTO-GENERATED by scripts/fetch-destination-images.ts - do not edit by hand.
// Source: Wikipedia / Wikimedia Commons (keyless MediaWiki API). Generated: 2026-06-22
// 55/56 destinations have an image. Images are CC-licensed;
// 'attribution' + 'license' + 'sourceUrl' are stored so the UI can credit authors.
// Re-run: npx tsx scripts/fetch-destination-images.ts

export interface DestinationImage {
  url: string
  width: number
  height: number
  attribution: string
  license: string
  sourceUrl: string
}

export const DESTINATION_IMAGES: Record<string, DestinationImage> = {
  "ooty": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Ooty_lake.jpg/960px-Ooty_lake.jpg",
    "width": 800,
    "height": 435,
    "attribution": "Vinayaraj",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ooty_lake.jpg"
  },
  "coonoor": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/CoonoorPanorama.jpg/960px-CoonoorPanorama.jpg",
    "width": 800,
    "height": 451,
    "attribution": "Hitoubashira",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:CoonoorPanorama.jpg"
  },
  "kotagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b0/Kotagiri_Town.jpg/960px-Kotagiri_Town.jpg",
    "width": 800,
    "height": 369,
    "attribution": "Sudarshia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kotagiri_Town.jpg"
  },
  "kodaikanal": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Boating_in_Kodaikanal_Lake_with_Mist.jpg/960px-Boating_in_Kodaikanal_Lake_with_Mist.jpg",
    "width": 800,
    "height": 533,
    "attribution": "KARTY JazZ",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Boating_in_Kodaikanal_Lake_with_Mist.jpg"
  },
  "yercaud": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Yercaud_lake.jpg/960px-Yercaud_lake.jpg",
    "width": 800,
    "height": 409,
    "attribution": "Riju K",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yercaud_lake.jpg"
  },
  "valparai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Tea_Estates_in_Valparai.jpg/960px-Tea_Estates_in_Valparai.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Kkdi63",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tea_Estates_in_Valparai.jpg"
  },
  "yelagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/01Yelagiri_Hills.jpg/960px-01Yelagiri_Hills.jpg",
    "width": 800,
    "height": 600,
    "attribution": "mckaysavage",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:01Yelagiri_Hills.jpg"
  },
  "kolli-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Kollimalai_milagu_Thottam.JPG/960px-Kollimalai_milagu_Thottam.JPG",
    "width": 800,
    "height": 450,
    "attribution": "Kollihillskarthi",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kollimalai_milagu_Thottam.JPG"
  },
  "megamalai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/Theniviewfromforestroad1.jpg/960px-Theniviewfromforestroad1.jpg",
    "width": 800,
    "height": 450,
    "attribution": "Thenikumar",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Theniviewfromforestroad1.jpg"
  },
  "topslip": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Uday_Kiran_Elephants_quarrel.jpg/960px-Uday_Kiran_Elephants_quarrel.jpg",
    "width": 800,
    "height": 533,
    "attribution": "UdayKiran28",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Uday_Kiran_Elephants_quarrel.jpg"
  },
  "sirumalai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d5/Sirumalai.jpg/960px-Sirumalai.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Dr. Chinchu C.",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sirumalai.jpg"
  },
  "javadi-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Javadi_Hills.jpg/960px-Javadi_Hills.jpg",
    "width": 800,
    "height": 421,
    "attribution": "Karthik Easvur",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Javadi_Hills.jpg"
  },
  "kalrayan-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/View_of_Kalvarayan_Hills_from_Arasampattu.jpg/960px-View_of_Kalvarayan_Hills_from_Arasampattu.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Thamizhpparithi Maari",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Kalvarayan_Hills_from_Arasampattu.jpg"
  },
  "pachamalai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fb/Rock_Fortress_-_Tiruchirappalli_-_India.JPG/960px-Rock_Fortress_-_Tiruchirappalli_-_India.JPG",
    "width": 800,
    "height": 600,
    "attribution": "Adam Jones Adam63",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Rock_Fortress_-_Tiruchirappalli_-_India.JPG"
  },
  "gudalur": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/View_of_Needle_Rock_View_Point.jpg/960px-View_of_Needle_Rock_View_Point.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Raj",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Needle_Rock_View_Point.jpg"
  },
  "mudumalai": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/Tiger_Drinking_Pond_Mudumalai_Mar21_DSC01310.jpg/960px-Tiger_Drinking_Pond_Mudumalai_Mar21_DSC01310.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Timothy A. Gonsalves",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tiger_Drinking_Pond_Mudumalai_Mar21_DSC01310.jpg"
  },
  "munnar": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Munnar_Overview.jpg/960px-Munnar_Overview.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Kondephy",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Munnar_Overview.jpg"
  },
  "wayanad": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Blue%2C_Green_%26_White.jpg/960px-Blue%2C_Green_%26_White.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Karkiabhijeet",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blue,_Green_%26_White.jpg"
  },
  "vythiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7d/Kerala_Veterinary_and_Animal_Sciences_University_05918.JPG/960px-Kerala_Veterinary_and_Animal_Sciences_University_05918.JPG",
    "width": 800,
    "height": 533,
    "attribution": "Vengolis",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kerala_Veterinary_and_Animal_Sciences_University_05918.JPG"
  },
  "thekkady": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Thekkady.jpg/960px-Thekkady.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Jigyasu",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thekkady.jpg"
  },
  "vagamon": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/Vagamon_meadows.JPG/960px-Vagamon_meadows.JPG",
    "width": 800,
    "height": 576,
    "attribution": "Visakh wiki",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Vagamon_meadows.JPG"
  },
  "ponmudi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d7/Morning_at_Ponmudi.jpg/960px-Morning_at_Ponmudi.jpg",
    "width": 800,
    "height": 430,
    "attribution": "Arunelectra",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Morning_at_Ponmudi.jpg"
  },
  "nelliyampathy": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/14/The_Western_Ghats003.jpg/960px-The_Western_Ghats003.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Shagil Kannur",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Western_Ghats003.jpg"
  },
  "peermade": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/TeaPlantationPambanar_20080216-1.jpg/960px-TeaPlantationPambanar_20080216-1.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Hans A. Rosbach",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:TeaPlantationPambanar_20080216-1.jpg"
  },
  "devikulam": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/40/Tea_plantations_at_Devikulam_in_2016.jpg/960px-Tea_plantations_at_Devikulam_in_2016.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Varkeyparakkal",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tea_plantations_at_Devikulam_in_2016.jpg"
  },
  "marayoor": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/9/93/Kovilkadavu.jpg",
    "width": 640,
    "height": 480,
    "attribution": "{{subst:usernamexpand:Cyrillic}}",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kovilkadavu.jpg"
  },
  "lakkidi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Blue%2C_Green_%26_White.jpg/960px-Blue%2C_Green_%26_White.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Karkiabhijeet",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Blue,_Green_%26_White.jpg"
  },
  "ramakkalmedu": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Statue_of_Kuruvan_%26_Kuruthi.jpg/960px-Statue_of_Kuruvan_%26_Kuruthi.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Augustus Binu : flickr",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Statue_of_Kuruvan_%26_Kuruthi.jpg"
  },
  "gavi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Gavi%2C_Kerala.jpg/960px-Gavi%2C_Kerala.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Samson Joseph",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gavi,_Kerala.jpg"
  },
  "silent-valley": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/SAN_BIRDS_48.jpg/960px-SAN_BIRDS_48.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Sancia Morris",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:SAN_BIRDS_48.jpg"
  },
  "eravikulam": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/AnaimudiPeak_DSC_4834.jpg/960px-AnaimudiPeak_DSC_4834.jpg",
    "width": 800,
    "height": 534,
    "attribution": "Mdmadhu",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:AnaimudiPeak_DSC_4834.jpg"
  },
  "coorg": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/02/Raja%27s_Seat_View_Point.jpg/960px-Raja%27s_Seat_View_Point.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Pawanrao",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Raja%27s_Seat_View_Point.jpg"
  },
  "chikmagalur": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Chikmagalur%2C_India._%287793316622%29.jpg/960px-Chikmagalur%2C_India._%287793316622%29.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Prof. Mohamed Shareef from Mysore",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chikmagalur,_India._(7793316622).jpg"
  },
  "sakleshpur": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Places_in_western_ghat_karntataka_between_subramanya_and_sakleshpur_14.jpg/960px-Places_in_western_ghat_karntataka_between_subramanya_and_sakleshpur_14.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Iamg",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Places_in_western_ghat_karntataka_between_subramanya_and_sakleshpur_14.jpg"
  },
  "kemmanagundi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/6/64/Kemmangundi_fog.JPG",
    "width": 426,
    "height": 320,
    "attribution": "Amarrg at English Wikipedia",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kemmangundi_fog.JPG"
  },
  "nandi-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Sunrise_at_Nandi_Hills.jpg/960px-Sunrise_at_Nandi_Hills.jpg",
    "width": 800,
    "height": 533,
    "attribution": "JzG",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sunrise_at_Nandi_Hills.jpg"
  },
  "kudremukh": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3c/Shola_Grasslands_and_forests_in_the_Kudremukh_National_Park%2C_Western_Ghats%2C_Karnataka.jpg/960px-Shola_Grasslands_and_forests_in_the_Kudremukh_National_Park%2C_Western_Ghats%2C_Karnataka.jpg",
    "width": 800,
    "height": 578,
    "attribution": "Karunakar Rayker",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shola_Grasslands_and_forests_in_the_Kudremukh_National_Park,_Western_Ghats,_Karnataka.jpg"
  },
  "agumbe": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4d/Agumbe_View_point.jpg/960px-Agumbe_View_point.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Shashidhara halady",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Agumbe_View_point.jpg"
  },
  "br-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hokkubare_Honnebare_peaks_BR_Hills.jpeg/960px-Hokkubare_Honnebare_peaks_BR_Hills.jpeg",
    "width": 800,
    "height": 600,
    "attribution": "Prashanthns",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hokkubare_Honnebare_peaks_BR_Hills.jpeg"
  },
  "mullayanagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/d/db/Chikmagalur%2C_India._%287793316622%29.jpg/960px-Chikmagalur%2C_India._%287793316622%29.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Prof. Mohamed Shareef from Mysore",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chikmagalur,_India._(7793316622).jpg"
  },
  "baba-budangiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ac/A_scenery_from_bababudan_hill.jpg/960px-A_scenery_from_bababudan_hill.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Pavankumar.nk",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_scenery_from_bababudan_hill.jpg"
  },
  "kodachadri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Kodachadri.JPG/960px-Kodachadri.JPG",
    "width": 800,
    "height": 600,
    "attribution": "Magentic Manifestations",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kodachadri.JPG"
  },
  "kabini": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Kabani_River.jpg/960px-Kabani_River.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Vinodnellackal at en.wikipedia",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kabani_River.jpg"
  },
  "devarayanadurga": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Yoga_Narasimha_Temple_Devarayanadurga.JPG/960px-Yoga_Narasimha_Temple_Devarayanadurga.JPG",
    "width": 800,
    "height": 532,
    "attribution": "Srinivasa83",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yoga_Narasimha_Temple_Devarayanadurga.JPG"
  },
  "skandagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a8/Skandagiri.jpg/960px-Skandagiri.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Vijets at English Wikipedia",
    "license": "Public domain",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Skandagiri.jpg"
  },
  "charmadi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/18/Charmadi_Ghat_Road.jpg/960px-Charmadi_Ghat_Road.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Vikramkkl",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Charmadi_Ghat_Road.jpg"
  },
  "mandalpatti": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Mandalpatti_Hills.jpg/960px-Mandalpatti_Hills.jpg",
    "width": 800,
    "height": 450,
    "attribution": "RN Satyanarayana rao",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mandalpatti_Hills.jpg"
  },
  "savandurga": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5b/Savandurga_Hill_02.jpg/960px-Savandurga_Hill_02.jpg",
    "width": 800,
    "height": 534,
    "attribution": "Pravega",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Savandurga_Hill_02.jpg"
  },
  "araku-valley": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/b/b0/Araku-valley.jpg",
    "width": 620,
    "height": 412,
    "attribution": "Eswararaokenguva",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Araku-valley.jpg"
  },
  "horsley-hills": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Annamacharya.jpg/960px-Annamacharya.jpg",
    "width": 800,
    "height": 1200,
    "attribution": "Tallapragada sriram",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Annamacharya.jpg"
  },
  "lambasingi": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Valley_near_lambasinghi.jpg/960px-Valley_near_lambasinghi.jpg",
    "width": 800,
    "height": 600,
    "attribution": "IM3847",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Valley_near_lambasinghi.jpg"
  },
  "maredumilli": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Maredumilli.jpg/960px-Maredumilli.jpg",
    "width": 800,
    "height": 1200,
    "attribution": "Mohanrangaphotography",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Maredumilli.jpg"
  },
  "nallamala": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/90/Hill_on_Top_of_Nallamalla_Hills_which_is_visible_on_the_way_to_Kadalivanam_which_is_more_than_20_Kms_from_Sri_sailam_temple.jpg/960px-Hill_on_Top_of_Nallamalla_Hills_which_is_visible_on_the_way_to_Kadalivanam_which_is_more_than_20_Kms_from_Sri_sailam_temple.jpg",
    "width": 800,
    "height": 600,
    "attribution": "Santoshtherock",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hill_on_Top_of_Nallamalla_Hills_which_is_visible_on_the_way_to_Kadalivanam_which_is_more_than_20_Kms_from_Sri_sailam_temple.jpg"
  },
  "ananthagiri": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Ananthagiri_Hills.JPG/960px-Ananthagiri_Hills.JPG",
    "width": 800,
    "height": 530,
    "attribution": "Praveen120",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ananthagiri_Hills.JPG"
  },
  "puducherry": {
    "url": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Pondicherry-Rock_beach_aerial_view.jpg/960px-Pondicherry-Rock_beach_aerial_view.jpg",
    "width": 800,
    "height": 533,
    "attribution": "Karthik Easvur",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pondicherry-Rock_beach_aerial_view.jpg"
  }
}

export function destinationImage(slug: string): DestinationImage | undefined {
  return DESTINATION_IMAGES[slug]
}
