// AUTO-GENERATED by scripts/fetch-destination-images.ts - do not edit by hand.
// Source: Wikimedia Commons (keyless MediaWiki API). Generated: 2026-06-28
// Images are NATURE-biased (scored toward landscapes/forests/wildlife, away from
// towns/buildings) then downloaded + self-hosted under public/dest-images/ so
// next/image never hits Wikimedia at runtime. 92/97 resolved.
// CC-licensed; 'attribution' + 'license' + 'sourceUrl' credit authors.
// Re-run: npx tsx scripts/fetch-destination-images.ts

export interface DestinationImage {
  url: string        // local path - full-screen hero
  thumbUrl: string   // local path - card grids (next/image sizes per device)
  width: number
  height: number
  attribution: string
  license: string
  sourceUrl: string
}

export const DESTINATION_IMAGES: Record<string, DestinationImage> = {
  "ooty": {
    "url": "/dest-images/ooty.jpg",
    "thumbUrl": "/dest-images/ooty.jpg",
    "width": 1920,
    "height": 1281,
    "attribution": "Fruiticos",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nilgiri_hills_view_from_Doddabetta_Peak.jpg"
  },
  "coonoor": {
    "url": "/dest-images/coonoor.jpg",
    "thumbUrl": "/dest-images/coonoor.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Gauri Wur Sem",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tea_Estate_-_Wald_-_Valley,_Coonoor.JPG"
  },
  "kotagiri": {
    "url": "/dest-images/kotagiri.jpg",
    "thumbUrl": "/dest-images/kotagiri.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Shanmugamp7",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_near_Catherine_Falls,_Kotagiri_(2).jpg"
  },
  "kodaikanal": {
    "url": "/dest-images/kodaikanal.jpg",
    "thumbUrl": "/dest-images/kodaikanal.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Rainer Halama",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kodaikanal_Wildlife_Sanctuary-_Pillar_Rocks-WUS05116-Pano.jpg"
  },
  "yercaud": {
    "url": "/dest-images/yercaud.jpg",
    "thumbUrl": "/dest-images/yercaud.jpg",
    "width": 1920,
    "height": 886,
    "attribution": "Ranjithkanth Tamilselvan J",
    "license": "CC0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Yercaud_pagoda_point_view.jpg"
  },
  "valparai": {
    "url": "/dest-images/valparai.jpg",
    "thumbUrl": "/dest-images/valparai.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Divyacskn1289",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sholayar_Dam.jpg"
  },
  "yelagiri": {
    "url": "/dest-images/yelagiri.jpg",
    "thumbUrl": "/dest-images/yelagiri.jpg",
    "width": 1920,
    "height": 1441,
    "attribution": "McKay Savage from London, UK",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:India_-_Yelagiri_Hills_Adventure_Camp_-_04_-_amazing_bird_nest_(4031747586).jpg"
  },
  "kolli-hills": {
    "url": "/dest-images/kolli-hills.jpg",
    "thumbUrl": "/dest-images/kolli-hills.jpg",
    "width": 1536,
    "height": 2048,
    "attribution": "Docku",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kolli_Hills_Waterfalls.JPG"
  },
  "megamalai": {
    "url": "/dest-images/megamalai.jpg",
    "thumbUrl": "/dest-images/megamalai.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "A. J. T. Johnsingh, WWF-India and NCF",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_view_of_Megamalai_Ghats,_AJT_Johnsingh._DSCN0744.jpg"
  },
  "topslip": {
    "url": "/dest-images/topslip.jpg",
    "thumbUrl": "/dest-images/topslip.jpg",
    "width": 1920,
    "height": 1286,
    "attribution": "Rangan Datta Wiki",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephant_Bathing,_Kozhikamuthi_Elephant_Camp_1.jpg"
  },
  "sirumalai": {
    "url": "/dest-images/sirumalai.jpg",
    "thumbUrl": "/dest-images/sirumalai.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "deadrat",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Dindigul_District_from_Sirumalai_Hills.jpg"
  },
  "javadi-hills": {
    "url": "/dest-images/javadi-hills.jpg",
    "thumbUrl": "/dest-images/javadi-hills.jpg",
    "width": 1598,
    "height": 3142,
    "attribution": "DRUID1962",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_Thousand_Year_Old_Tree,Jawadu_Hills_Forest,Eastern_Ghats_South_India.jpg"
  },
  "kalrayan-hills": {
    "url": "/dest-images/kalrayan-hills.jpg",
    "thumbUrl": "/dest-images/kalrayan-hills.jpg",
    "width": 1920,
    "height": 1272,
    "attribution": "PJeganathan",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Megam_Falls_in_kalvarayan_hills_JEG3621.jpg"
  },
  "gudalur": {
    "url": "/dest-images/gudalur.jpg",
    "thumbUrl": "/dest-images/gudalur.jpg",
    "width": 1295,
    "height": 971,
    "attribution": "Jaseem Hamza",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gudalur_views_from_Needle_Rock_View_Point_-_panoramio.jpg"
  },
  "mudumalai": {
    "url": "/dest-images/mudumalai.jpg",
    "thumbUrl": "/dest-images/mudumalai.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Timothy A. Gonsalves",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moyar_River_Camp_Elephant_Bath_Mudumalai_Mar21_A7C_00333.jpg"
  },
  "munnar": {
    "url": "/dest-images/munnar.jpg",
    "thumbUrl": "/dest-images/munnar.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "yjenith",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_from_Munnar_Tea_estate,_Kerala.jpg"
  },
  "wayanad": {
    "url": "/dest-images/wayanad.jpg",
    "thumbUrl": "/dest-images/wayanad.jpg",
    "width": 1920,
    "height": 746,
    "attribution": "Ingo Mehling",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:En_Ooru_-_Chembra_Peak_View.jpg"
  },
  "vythiri": {
    "url": "/dest-images/vythiri.jpg",
    "thumbUrl": "/dest-images/vythiri.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Athulvis",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Tea_plantation_in_Vythiri_3.jpg"
  },
  "thekkady": {
    "url": "/dest-images/thekkady.jpg",
    "thumbUrl": "/dest-images/thekkady.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Sreedevi512",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:A_view_of_Periyar_Wildlife_Sanctuary_from_boat.jpg"
  },
  "vagamon": {
    "url": "/dest-images/vagamon.jpg",
    "thumbUrl": "/dest-images/vagamon.jpg",
    "width": 1920,
    "height": 1275,
    "attribution": "shankar s. from Dubai, united arab emirates",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Fabulous_mountain_scenery_and_tea_gardens!_(28760915925).jpg"
  },
  "ponmudi": {
    "url": "/dest-images/ponmudi.jpg",
    "thumbUrl": "/dest-images/ponmudi.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Arunram85",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Green_lush_kerala_02.jpg"
  },
  "nelliyampathy": {
    "url": "/dest-images/nelliyampathy.jpg",
    "thumbUrl": "/dest-images/nelliyampathy.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "WikiSantaClaus",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_Of_Pothundy_Dam_(15th_January_2026).jpg"
  },
  "peermade": {
    "url": "/dest-images/peermade.jpg",
    "thumbUrl": "/dest-images/peermade.jpg",
    "width": 1280,
    "height": 960,
    "attribution": "No machine-readable author provided. Soman assumed (based on copyright claims).",
    "license": "CC BY-SA 2.5",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peermade-2006.JPG"
  },
  "devikulam": {
    "url": "/dest-images/devikulam.jpg",
    "thumbUrl": "/dest-images/devikulam.jpg",
    "width": 1920,
    "height": 424,
    "attribution": "Dpradeepkumar",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lokhart_Tea_Estate,Devikulam,Kerala.jpg"
  },
  "marayoor": {
    "url": "/dest-images/marayoor.jpg",
    "thumbUrl": "/dest-images/marayoor.jpg",
    "width": 1532,
    "height": 860,
    "attribution": "Jaseem Hamza",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Thoovanam_Waterfalls_@_Chinnar_Wildlife_Sanctuary_-_panoramio_(1).jpg"
  },
  "lakkidi": {
    "url": "/dest-images/lakkidi.jpg",
    "thumbUrl": "/dest-images/lakkidi.jpg",
    "width": 1920,
    "height": 1081,
    "attribution": "Dinesh Valke from Thane, India",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:..._Lakkidi_View_Point_(49105587226).jpg"
  },
  "ramakkalmedu": {
    "url": "/dest-images/ramakkalmedu.jpg",
    "thumbUrl": "/dest-images/ramakkalmedu.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Kondephy",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ramakkalmedu_Rock_(landscape).jpg"
  },
  "gavi": {
    "url": "/dest-images/gavi.jpg",
    "thumbUrl": "/dest-images/gavi.jpg",
    "width": 1496,
    "height": 840,
    "attribution": "Jaseem Hamza",
    "license": "CC BY 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lake_@_Angamozhi_reserve_Forest_-_panoramio.jpg"
  },
  "silent-valley": {
    "url": "/dest-images/silent-valley.jpg",
    "thumbUrl": "/dest-images/silent-valley.jpg",
    "width": 1920,
    "height": 1277,
    "attribution": "Cj.samson",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Silentvalley_bridge.JPG"
  },
  "eravikulam": {
    "url": "/dest-images/eravikulam.jpg",
    "thumbUrl": "/dest-images/eravikulam.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Asheen Anoop",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nilgiri_Tahr_Eravikulam_National_Park.jpg"
  },
  "coorg": {
    "url": "/dest-images/coorg.jpg",
    "thumbUrl": "/dest-images/coorg.jpg",
    "width": 1920,
    "height": 2880,
    "attribution": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Coffee_Coconuts_Pepper_Estate_Coorg_Feb24_A7C_09365.jpg"
  },
  "chikmagalur": {
    "url": "/dest-images/chikmagalur.jpg",
    "thumbUrl": "/dest-images/chikmagalur.jpg",
    "width": 1920,
    "height": 1277,
    "attribution": "Anvesh1103",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mullayanagiri_peak.jpg"
  },
  "sakleshpur": {
    "url": "/dest-images/sakleshpur.jpg",
    "thumbUrl": "/dest-images/sakleshpur.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Shanmugamp7",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_from_Agani_peak,_Sakleshpur_(2).jpg"
  },
  "kemmanagundi": {
    "url": "/dest-images/kemmanagundi.jpg",
    "thumbUrl": "/dest-images/kemmanagundi.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Arunkm44",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kemmanagundi_View.jpg"
  },
  "nandi-hills": {
    "url": "/dest-images/nandi-hills.jpg",
    "thumbUrl": "/dest-images/nandi-hills.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Gupteshwari Sahu",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Landscape_nandihills.jpg"
  },
  "kudremukh": {
    "url": "/dest-images/kudremukh.jpg",
    "thumbUrl": "/dest-images/kudremukh.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "iMahesh",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trekking_trail_on_Netravati_peak.jpg"
  },
  "agumbe": {
    "url": "/dest-images/agumbe.jpg",
    "thumbUrl": "/dest-images/agumbe.jpg",
    "width": 1920,
    "height": 1081,
    "attribution": "Dinesh Valke from Thane, India",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_from_sunset_point,_Agumbe_(16017939927).jpg"
  },
  "br-hills": {
    "url": "/dest-images/br-hills.jpg",
    "thumbUrl": "/dest-images/br-hills.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dry_Forest_SH-80_K_Gudi_BR_Hills_Karnataka_May24_A7CR_00062.jpg"
  },
  "mullayanagiri": {
    "url": "/dest-images/mullayanagiri.jpg",
    "thumbUrl": "/dest-images/mullayanagiri.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Avinash Kumar singh",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_from_the_top_of_mullayanagiri_peak.jpg"
  },
  "baba-budangiri": {
    "url": "/dest-images/baba-budangiri.jpg",
    "thumbUrl": "/dest-images/baba-budangiri.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "iMahesh",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Landscapes_of_Western_Ghats_from_Mullayyanagiri_Betta.jpg"
  },
  "kodachadri": {
    "url": "/dest-images/kodachadri.jpg",
    "thumbUrl": "/dest-images/kodachadri.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Azam148",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kodachadri_trek_waterfalls.jpg"
  },
  "kabini": {
    "url": "/dest-images/kabini.jpg",
    "thumbUrl": "/dest-images/kabini.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Rohit Varma",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephant_Family_(109833051).jpeg"
  },
  "devarayanadurga": {
    "url": "/dest-images/devarayanadurga.jpg",
    "thumbUrl": "/dest-images/devarayanadurga.jpg",
    "width": 1920,
    "height": 1083,
    "attribution": "Psubhashish",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Devarayanadurga_hills_from_Janastu_campus.jpg"
  },
  "skandagiri": {
    "url": "/dest-images/skandagiri.jpg",
    "thumbUrl": "/dest-images/skandagiri.jpg",
    "width": 1920,
    "height": 880,
    "attribution": "Aranyaparva",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Cloud_over_Skandagiri_hills.jpg"
  },
  "charmadi": {
    "url": "/dest-images/charmadi.jpg",
    "thumbUrl": "/dest-images/charmadi.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Golden boy arsh varna",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Charmadi_Ghat_view_point.jpg"
  },
  "mandalpatti": {
    "url": "/dest-images/mandalpatti.jpg",
    "thumbUrl": "/dest-images/mandalpatti.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Vistarphotos",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:PA230347_cloud_lake_spills_over_ps.jpg"
  },
  "savandurga": {
    "url": "/dest-images/savandurga.jpg",
    "thumbUrl": "/dest-images/savandurga.jpg",
    "width": 1920,
    "height": 1275,
    "attribution": "S S Kalaakaar",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hill_Station_Of_%22_Savanadurga_%22_the_largest_monolith_hills_in_Asia.jpg"
  },
  "araku-valley": {
    "url": "/dest-images/araku-valley.jpg",
    "thumbUrl": "/dest-images/araku-valley.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Pinakpani",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Araku_Valley_coffee_plantations_in_Ananthagiri_hills_in_Andhra_Pradesh_01.jpg"
  },
  "horsley-hills": {
    "url": "/dest-images/horsley-hills.jpg",
    "thumbUrl": "/dest-images/horsley-hills.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "NAYASHA WIKI",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:HORSELEYHILLS_01.jpg"
  },
  "lambasingi": {
    "url": "/dest-images/lambasingi.jpg",
    "thumbUrl": "/dest-images/lambasingi.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Varun37",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Hills_clouds.jpg"
  },
  "maredumilli": {
    "url": "/dest-images/maredumilli.jpg",
    "thumbUrl": "/dest-images/maredumilli.jpg",
    "width": 1920,
    "height": 809,
    "attribution": "S. Sri Harsha",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MAREDUMILLI_-_river_from_the_falls.jpg"
  },
  "nallamala": {
    "url": "/dest-images/nallamala.jpg",
    "thumbUrl": "/dest-images/nallamala.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Dubbala Divya",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nallamala_forest_view_01.jpg"
  },
  "ananthagiri": {
    "url": "/dest-images/ananthagiri.jpg",
    "thumbUrl": "/dest-images/ananthagiri.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Tanukusreeharsha",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Ananthagiri_Hills_Trekking_Area.jpg"
  },
  "puducherry": {
    "url": "/dest-images/puducherry.jpg",
    "thumbUrl": "/dest-images/puducherry.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Rupam Dey",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sunrise_of_Poducherry.jpg"
  },
  "srinagar": {
    "url": "/dest-images/srinagar.jpg",
    "thumbUrl": "/dest-images/srinagar.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Shubhamsharma021",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dal_lake_mountain_view.jpg"
  },
  "gulmarg": {
    "url": "/dest-images/gulmarg.jpg",
    "thumbUrl": "/dest-images/gulmarg.jpg",
    "width": 1920,
    "height": 1920,
    "attribution": "Mutahir Showkat",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sunset_at_Gulmarg_December_2020_by_Mutahir_Showkat.jpg"
  },
  "pahalgam": {
    "url": "/dest-images/pahalgam.jpg",
    "thumbUrl": "/dest-images/pahalgam.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "CuriousZil",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pahalgam_Valley_View.jpg"
  },
  "sonamarg": {
    "url": "/dest-images/sonamarg.jpg",
    "thumbUrl": "/dest-images/sonamarg.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Pranav Joshi",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sonmarg_Valley.JPG"
  },
  "doodhpathri": {
    "url": "/dest-images/doodhpathri.jpg",
    "thumbUrl": "/dest-images/doodhpathri.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Ankur P from Pune, India",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Meadows_and_Forests_Doodhpathri_southwest_Jammu_Kashmir_India.jpg"
  },
  "yusmarg": {
    "url": "/dest-images/yusmarg.jpg",
    "thumbUrl": "/dest-images/yusmarg.jpg",
    "width": 1920,
    "height": 1081,
    "attribution": "Suhail Skindar Sofi",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nilnag_Lake.jpg"
  },
  "gurez-valley": {
    "url": "/dest-images/gurez-valley.jpg",
    "thumbUrl": "/dest-images/gurez-valley.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Journo Mohsin",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Gurez_Valley_04.jpg"
  },
  "patnitop": {
    "url": "/dest-images/patnitop.jpg",
    "thumbUrl": "/dest-images/patnitop.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Shailendrachauhan95",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Patnitop_Hill_7.jpg"
  },
  "bhaderwah": {
    "url": "/dest-images/bhaderwah.jpg",
    "thumbUrl": "/dest-images/bhaderwah.jpg",
    "width": 1920,
    "height": 3950,
    "attribution": "Pranav.jain25",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Jai_Ghati-_bhaderwah-jammu-jammu_and_kashmir.jpg"
  },
  "sinthan-top": {
    "url": "/dest-images/sinthan-top.jpg",
    "thumbUrl": "/dest-images/sinthan-top.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Ashoksngh2010",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Sinthan_top,_Srinagar.jpg"
  },
  "leh": {
    "url": "/dest-images/leh.jpg",
    "thumbUrl": "/dest-images/leh.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "Uniweb Toulouse",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mountain_landscape_with_a_river_close_to_Leh_Ladakh.jpg"
  },
  "nubra-valley": {
    "url": "/dest-images/nubra-valley.jpg",
    "thumbUrl": "/dest-images/nubra-valley.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Yuvraj Anand",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Peaceful_landscape_with_rocks,_sand_dunes,_trees_and_river_in_Nubra_Valley,_Ladakh.jpg"
  },
  "pangong-tso": {
    "url": "/dest-images/pangong-tso.jpg",
    "thumbUrl": "/dest-images/pangong-tso.jpg",
    "width": 1920,
    "height": 621,
    "attribution": "Krzysztof Popławski",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panoramic_view_of_Pnagong_lake,_Pangong_Tso,_view_form_Pangong_Lake_Rd,_194201.jpg"
  },
  "khardung-la": {
    "url": "/dest-images/khardung-la.jpg",
    "thumbUrl": "/dest-images/khardung-la.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Vyacheslav Argenberg",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Khardung_La_(pass),_Mountains,_Indus_River_Valley,_Ladakh,_North_India,_Himalayas.jpg"
  },
  "tso-moriri": {
    "url": "/dest-images/tso-moriri.jpg",
    "thumbUrl": "/dest-images/tso-moriri.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "McKay Savage from London, UK",
    "license": "CC BY 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:India_-_Ladakh_-_Trekking_-_113_-_final_river_valley_towards_Tso_Moriri_(3906559436).jpg"
  },
  "lamayuru": {
    "url": "/dest-images/lamayuru.jpg",
    "thumbUrl": "/dest-images/lamayuru.jpg",
    "width": 1920,
    "height": 1080,
    "attribution": "MandarUrankarM",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Moonland_valley_3.jpg"
  },
  "zanskar": {
    "url": "/dest-images/zanskar.jpg",
    "thumbUrl": "/dest-images/zanskar.jpg",
    "width": 1920,
    "height": 760,
    "attribution": "This Photo was taken by Timothy A. Gonsalves. Feel free to use my photos, but pl",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Padum_Valley_Panorama_Zanskar_Oct22_A7C_03968-69_Pano.jpg"
  },
  "shimla": {
    "url": "/dest-images/shimla.jpg",
    "thumbUrl": "/dest-images/shimla.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Gayatri Priyadarshini",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Shimla_nature_landscape.jpg"
  },
  "manali": {
    "url": "/dest-images/manali.jpg",
    "thumbUrl": "/dest-images/manali.jpg",
    "width": 1280,
    "height": 960,
    "attribution": "Muku26",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:MOUNTAIN_View.jpg"
  },
  "rohtang-pass": {
    "url": "/dest-images/rohtang-pass.jpg",
    "thumbUrl": "/dest-images/rohtang-pass.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Timothy Gonsalves",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chandra_River_from_Rohtang_Himachal_Jul19.jpg"
  },
  "dharamshala": {
    "url": "/dest-images/dharamshala.jpg",
    "thumbUrl": "/dest-images/dharamshala.jpg",
    "width": 1920,
    "height": 2560,
    "attribution": "Tanvi.sharmaaa",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Slate_Mountain_at_Kharota_Valley.jpg"
  },
  "dalhousie": {
    "url": "/dest-images/dalhousie.jpg",
    "thumbUrl": "/dest-images/dalhousie.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Snigdhabafna",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Dalhousie_sunset_from_the_hills.jpg"
  },
  "khajjiar": {
    "url": "/dest-images/khajjiar.jpg",
    "thumbUrl": "/dest-images/khajjiar.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Wittystef",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Khajjiar_lake.jpg"
  },
  "kasol": {
    "url": "/dest-images/kasol.jpg",
    "thumbUrl": "/dest-images/kasol.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Alok Kumar",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Parvati_Valley_river_kasol.jpg"
  },
  "kalpa": {
    "url": "/dest-images/kalpa.jpg",
    "thumbUrl": "/dest-images/kalpa.jpg",
    "width": 1920,
    "height": 973,
    "attribution": "Anubhav Agarwal",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kinner_Kailash_Mountain_Range.jpg"
  },
  "chitkul": {
    "url": "/dest-images/chitkul.jpg",
    "thumbUrl": "/dest-images/chitkul.jpg",
    "width": 1920,
    "height": 1137,
    "attribution": "Sukanya Ray",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Baspa_river_flowing_through_Chitkul.jpg"
  },
  "spiti-valley": {
    "url": "/dest-images/spiti-valley.jpg",
    "thumbUrl": "/dest-images/spiti-valley.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Mike Shaw",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_fields_from_Key_Gompa_monastery,_Spiti_Valley,_Himachal_Pradesh,_India_02.jpg"
  },
  "tirthan-valley": {
    "url": "/dest-images/tirthan-valley.jpg",
    "thumbUrl": "/dest-images/tirthan-valley.jpg",
    "width": 1920,
    "height": 1275,
    "attribution": "Ankitwadhwa10",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Trekking_Bridge.jpg"
  },
  "mussoorie": {
    "url": "/dest-images/mussoorie.jpg",
    "thumbUrl": "/dest-images/mussoorie.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Dherwalstudio",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Kempty_Falls_Hills_Near_Mussoorie.jpg"
  },
  "nainital": {
    "url": "/dest-images/nainital.jpg",
    "thumbUrl": "/dest-images/nainital.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Slyronit",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_of_Nainital_lake_from_Snow_View_Point.jpg"
  },
  "chopta": {
    "url": "/dest-images/chopta.jpg",
    "thumbUrl": "/dest-images/chopta.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Padmanabhan07",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chaukhamba_Peak.jpg"
  },
  "munsiyari": {
    "url": "/dest-images/munsiyari.jpg",
    "thumbUrl": "/dest-images/munsiyari.jpg",
    "width": 1920,
    "height": 1079,
    "attribution": "Pranavspn",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panchachuli_peaks_view_from_%22Thamri_Kund%22.JPG"
  },
  "valley-of-flowers": {
    "url": "/dest-images/valley-of-flowers.jpg",
    "thumbUrl": "/dest-images/valley-of-flowers.jpg",
    "width": 1920,
    "height": 1280,
    "attribution": "Original: Rohit Sharma Derivative work: UnpetitproleX",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Valley_of_flowers_national_park,_Uttarakhand,_India_03_(edit).jpg"
  },
  "kausani": {
    "url": "/dest-images/kausani.jpg",
    "thumbUrl": "/dest-images/kausani.jpg",
    "width": 1920,
    "height": 1440,
    "attribution": "Aru10491",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Pre-Sunset_Trisul,_Kausani.jpg"
  },
  "binsar": {
    "url": "/dest-images/binsar.jpg",
    "thumbUrl": "/dest-images/binsar.jpg",
    "width": 1280,
    "height": 2276,
    "attribution": "Rohit Gosain",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:View_from_Brahmadhungi,_Binsar_wildlife_sanctuary_20160520.jpg"
  },
  "rishikesh": {
    "url": "/dest-images/rishikesh.jpg",
    "thumbUrl": "/dest-images/rishikesh.jpg",
    "width": 1920,
    "height": 896,
    "attribution": "Vedrix",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Scenic_View_of_Rishikesh_with_Ganga_River_and_Hills_in_Background.jpg"
  },
  "hemis": {
    "url": "/dest-images/hemis.jpg",
    "thumbUrl": "/dest-images/hemis.jpg",
    "width": 1920,
    "height": 960,
    "attribution": "Prithwiraj Dhang",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Landscape_Hemis_National_Park.jpg"
  },
  "auli": {
    "url": "/dest-images/auli.jpg",
    "thumbUrl": "/dest-images/auli.jpg",
    "width": 1920,
    "height": 1071,
    "attribution": "Bibek Raj Pandeya",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Mountain_Nanda_Devi_seen_from_Auli.jpg"
  }
}

export function destinationImage(slug: string): DestinationImage | undefined {
  return DESTINATION_IMAGES[slug]
}
