// EV charging across South India, organised BY DISTRICT.
//
// Honest scope: a hand-maintained file can NOT list every charger (Chennai alone
// has 130+). So this does two things:
//   1. Curated, map-placed stations we can name from public network data
//      (Tata Power, Statiq, Ather, Zeon, chargeMOD, KSEB, OnePlug, BPCL, Ola).
//   2. A DISTRICT DIRECTORY covering every district we care about - each links
//      out to the live, always-current sources (Google Maps + govt e-AMRIT map)
//      so completeness never depends on us hand-copying pins that go stale.
//
// ⚠ Always verify availability in the operator's app before relying on a stop.

export type Connector = 'CCS2' | 'CHAdeMO' | 'Type2' | 'Bharat_DC' | 'Bharat_AC'
export type ChargerSpeed = 'fast' | 'standard'
export type StationStatus = 'public' | 'guests_only' | 'hotel' | 'restaurant'

export interface EvStation {
  id: string
  name: string
  network: string
  area: string          // locality within the district
  district: string
  state: string
  lat: number
  lng: number
  connectors: Connector[]
  powerKw: number
  speed: ChargerSpeed
  status: StationStatus
  note?: string
}

// Open-data station (OSM / OCM), generated by scripts/fetch-ev-stations.ts.
// Same shape as a curated station plus provenance + nearest-hill-station linkage.
export interface OsmEvStation extends EvStation {
  source: 'osm' | 'ocm'
  nearestDestSlug: string | null
  distanceToDestKm: number | null
}

export interface DistrictEntry {
  district: string
  state: string
  blurb?: string
}

// Every South-Indian district we surface - each gets live "see all" links even
// when we have no curated pins yet. Order = rough travel relevance.
export const DISTRICT_DIRECTORY: DistrictEntry[] = [
  // Tamil Nadu
  { district: 'Chennai',          state: 'Tamil Nadu',     blurb: 'Biggest EV hub in the south - 130+ public points.' },
  { district: 'Coimbatore',       state: 'Tamil Nadu',     blurb: 'Last big charge before the Nilgiris ghats.' },
  { district: 'The Nilgiris',     state: 'Tamil Nadu',     blurb: 'Ooty, Coonoor, Kotagiri - mostly AC/hotel chargers.' },
  { district: 'Salem',            state: 'Tamil Nadu',     blurb: 'NH44 corridor + gateway to Yercaud.' },
  { district: 'Krishnagiri',      state: 'Tamil Nadu' },
  { district: 'Madurai',          state: 'Tamil Nadu' },
  { district: 'Dindigul',         state: 'Tamil Nadu',     blurb: 'Charge here before the Kodaikanal ghat.' },
  { district: 'Tiruchirappalli',  state: 'Tamil Nadu' },
  { district: 'Vellore',          state: 'Tamil Nadu' },
  { district: 'Tirunelveli',      state: 'Tamil Nadu' },
  // Puducherry
  { district: 'Puducherry',       state: 'Puducherry',     blurb: 'Compact union territory - chargers along ECR & town.' },
  // Karnataka
  { district: 'Bengaluru Urban',  state: 'Karnataka',      blurb: 'Dense network - start point for Coorg/Chikmagalur.' },
  { district: 'Mysuru',           state: 'Karnataka',      blurb: 'Split point for Coorg & Wayanad.' },
  { district: 'Kodagu (Coorg)',   state: 'Karnataka' },
  { district: 'Chikkamagaluru',   state: 'Karnataka' },
  { district: 'Hassan',           state: 'Karnataka' },
  { district: 'Mandya',           state: 'Karnataka' },
  { district: 'Ramanagara',       state: 'Karnataka' },
  { district: 'Dakshina Kannada', state: 'Karnataka',      blurb: 'Mangaluru coast.' },
  // Kerala
  { district: 'Ernakulam',        state: 'Kerala',         blurb: 'Kochi - base for the Munnar climb.' },
  { district: 'Idukki',           state: 'Kerala',         blurb: 'Munnar & Thekkady - chargeMOD/KSEB coverage.' },
  { district: 'Wayanad',          state: 'Kerala' },
  { district: 'Thiruvananthapuram', state: 'Kerala' },
  // Andhra Pradesh
  { district: 'Visakhapatnam',    state: 'Andhra Pradesh', blurb: 'Base for the Araku Valley drive.' },
  // Telangana
  { district: 'Hyderabad',        state: 'Telangana',      blurb: 'Base for Ananthagiri Hills.' },
]

export const STATES = ['Tamil Nadu', 'Puducherry', 'Karnataka', 'Kerala', 'Andhra Pradesh', 'Telangana'] as const

export const EV_STATIONS: EvStation[] = [
  // ─── CHENNAI (district hub - sample of the 130+; use live links for the rest) ─
  { id: 'che-lakshmi', name: 'Tata Power - Lakshmi Tata (30kW)', network: 'Tata Power', area: 'Little Mount, Guindy', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0095, lng: 80.2210, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'public' },
  { id: 'che-omr',     name: 'Tata Power - Taj Vivanta OMR (30kW)', network: 'Tata Power', area: 'Sholinganallur, OMR', district: 'Chennai', state: 'Tamil Nadu', lat: 12.9010, lng: 80.2279, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'hotel', note: 'Handy for OMR IT corridor.' },
  { id: 'che-egmore',  name: 'Statiq - Egmore CMRL Parking (60kW)', network: 'Statiq', area: 'Egmore', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0780, lng: 80.2609, connectors: ['CCS2', 'CHAdeMO'], powerKw: 60, speed: 'fast', status: 'public', note: 'Metro station parking - central.' },
  { id: 'che-conne',   name: 'Tata Power - Taj Connemara (30kW)', network: 'Tata Power', area: 'Anna Salai', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0604, lng: 80.2660, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'hotel' },
  { id: 'che-itc',     name: 'Statiq - ITC Grand Chola', network: 'Statiq', area: 'Guindy', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0103, lng: 80.2205, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'hotel' },
  { id: 'che-leela',   name: 'Statiq - The Leela Palace', network: 'Statiq', area: 'MRC Nagar', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0227, lng: 80.2820, connectors: ['Type2'], powerKw: 22, speed: 'standard', status: 'hotel' },
  { id: 'che-ather',   name: 'Ather Grid - Metrozone Towers', network: 'Ather', area: 'Anna Nagar West', district: 'Chennai', state: 'Tamil Nadu', lat: 13.0876, lng: 80.2010, connectors: ['Type2'], powerKw: 7.4, speed: 'standard', status: 'public', note: 'Primarily 2-wheeler / fast-charge points.' },

  // ─── PUDUCHERRY ──────────────────────────────────────────────────────────────
  { id: 'pdy-ginger',  name: 'Tata Power - Ginger Pondicherry', network: 'Tata Power', area: 'Krishna Nagar', district: 'Puducherry', state: 'Puducherry', lat: 11.9588, lng: 79.8120, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'hotel' },
  { id: 'pdy-ola',     name: 'Ola Hypercharger - BPCL Station', network: 'Ola Electric', area: 'Pakkamudayanpet, 100 Feet Rd', district: 'Puducherry', state: 'Puducherry', lat: 11.9300, lng: 79.8050, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'public', note: 'Ola Hypercharger network.' },
  { id: 'pdy-fpl',     name: 'Tata Power - FPL / MG Motors', network: 'Tata Power', area: 'Ariyankuppam, ECR', district: 'Puducherry', state: 'Puducherry', lat: 11.8920, lng: 79.8000, connectors: ['CCS2', 'CHAdeMO'], powerKw: 50, speed: 'fast', status: 'public', note: 'Open 24h, on the ECR.' },
  { id: 'pdy-clubm',   name: 'Statiq / Sunfuel - Club Mahindra Resort', network: 'Statiq', area: 'Bahour / Manapet', district: 'Puducherry', state: 'Puducherry', lat: 11.7900, lng: 79.8050, connectors: ['Type2'], powerKw: 22, speed: 'standard', status: 'hotel' },

  // ─── COIMBATORE (last big charge before the Nilgiris) ────────────────────────
  { id: 'cbe-oneplug', name: 'OnePlug DC Fast - Coimbatore', network: 'OnePlug', area: 'Avinashi Rd', district: 'Coimbatore', state: 'Tamil Nadu', lat: 11.0168, lng: 76.9558, connectors: ['CCS2', 'Type2'], powerKw: 120, speed: 'fast', status: 'public', note: 'Top up before the ghat climb.' },
  { id: 'cbe-mettu',   name: 'Statiq Charging - Mettupalayam', network: 'Statiq', area: 'Mettupalayam', district: 'Coimbatore', state: 'Tamil Nadu', lat: 11.2998, lng: 76.9510, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'public', note: 'Foot of the Coonoor ghat (40 hairpins).' },
  { id: 'cbe-pollachi',name: 'OnePlug - Pollachi (for Valparai)', network: 'OnePlug', area: 'Pollachi', district: 'Coimbatore', state: 'Tamil Nadu', lat: 10.6588, lng: 77.0085, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'public', note: 'Last charger before the Valparai ghat.' },

  // ─── THE NILGIRIS ────────────────────────────────────────────────────────────
  { id: 'nil-ooty',    name: 'EV Charging Station - Ooty', network: 'OnePlug', area: 'Ooty', district: 'The Nilgiris', state: 'Tamil Nadu', lat: 11.4102, lng: 76.6950, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'public' },
  { id: 'nil-gymk',    name: 'Wellington Gymkhana Club', network: 'Zeon', area: 'Coonoor', district: 'The Nilgiris', state: 'Tamil Nadu', lat: 11.3530, lng: 76.7959, connectors: ['Type2'], powerKw: 7.4, speed: 'standard', status: 'guests_only', note: 'Club guests only - call ahead.' },
  { id: 'nil-kotagiri',name: 'Lakshmi Holiday Resort', network: 'Zeon', area: 'Kotagiri', district: 'The Nilgiris', state: 'Tamil Nadu', lat: 11.4216, lng: 76.8606, connectors: ['Type2'], powerKw: 7.4, speed: 'standard', status: 'hotel' },

  // ─── SALEM ───────────────────────────────────────────────────────────────────
  { id: 'sal-tata',    name: 'Tata Power Hub - Salem', network: 'Tata Power', area: 'Salem', district: 'Salem', state: 'Tamil Nadu', lat: 11.6643, lng: 78.1460, connectors: ['CCS2', 'CHAdeMO'], powerKw: 60, speed: 'fast', status: 'public' },
  { id: 'sal-yercaud', name: 'EV Charging - Yercaud', network: 'Statiq', area: 'Yercaud', district: 'Salem', state: 'Tamil Nadu', lat: 11.7799, lng: 78.2090, connectors: ['Type2'], powerKw: 7.4, speed: 'standard', status: 'public' },

  // ─── KRISHNAGIRI ─────────────────────────────────────────────────────────────
  { id: 'kri-bpcl',    name: 'BPCL Fast Charger - Krishnagiri', network: 'BPCL', area: 'NH44', district: 'Krishnagiri', state: 'Tamil Nadu', lat: 12.5186, lng: 78.2137, connectors: ['CCS2'], powerKw: 50, speed: 'fast', status: 'public' },

  // ─── MADURAI / DINDIGUL ──────────────────────────────────────────────────────
  { id: 'mad-bpcl',    name: 'BPCL Fast Charger - Madurai', network: 'BPCL', area: 'Madurai', district: 'Madurai', state: 'Tamil Nadu', lat: 9.9252, lng: 78.1198, connectors: ['CCS2'], powerKw: 50, speed: 'fast', status: 'public' },
  { id: 'din-oneplug', name: 'OnePlug DC Fast - Dindigul', network: 'OnePlug', area: 'Dindigul', district: 'Dindigul', state: 'Tamil Nadu', lat: 10.3624, lng: 77.9695, connectors: ['CCS2', 'Type2'], powerKw: 60, speed: 'fast', status: 'public', note: 'Charge before the Kodai ghat (64 bends).' },
  { id: 'din-kodai',   name: 'Hotel Kodai International (Zeon 30kW)', network: 'Zeon', area: 'Kodaikanal', district: 'Dindigul', state: 'Tamil Nadu', lat: 10.2381, lng: 77.4892, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'hotel', note: 'Two DC CCS chargers.' },

  // ─── KARNATAKA - Bengaluru → Coorg/Chikmagalur ───────────────────────────────
  { id: 'blr-kadamba', name: 'The Hotel Kadamba (Zeon 25kW)', network: 'Zeon', area: 'Bidadi, Mysore Rd', district: 'Ramanagara', state: 'Karnataka', lat: 12.7980, lng: 77.3860, connectors: ['CCS2'], powerKw: 25, speed: 'fast', status: 'hotel', note: 'Start of NH275.' },
  { id: 'man-maddur',  name: 'BPCL Fast Charger - Maddur', network: 'BPCL', area: 'Maddur', district: 'Mandya', state: 'Karnataka', lat: 12.5847, lng: 77.0436, connectors: ['CCS2'], powerKw: 25, speed: 'fast', status: 'public' },
  { id: 'mys-tata',    name: 'Tata Power Hub - Mysuru', network: 'Tata Power', area: 'Mysuru', district: 'Mysuru', state: 'Karnataka', lat: 12.2958, lng: 76.6394, connectors: ['CCS2', 'CHAdeMO'], powerKw: 60, speed: 'fast', status: 'public', note: 'Split point for Coorg / Wayanad.' },
  { id: 'kod-kushal',  name: 'Statiq Charging - Kushalnagar', network: 'Statiq', area: 'Kushalnagar', district: 'Kodagu (Coorg)', state: 'Karnataka', lat: 12.4574, lng: 75.9560, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'public', note: 'Gateway to Madikeri.' },
  { id: 'kod-madikeri',name: 'EV Charging - Madikeri', network: 'Statiq', area: 'Madikeri', district: 'Kodagu (Coorg)', state: 'Karnataka', lat: 12.4244, lng: 75.7382, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'public' },
  { id: 'has-tata',    name: 'Tata Power Charger - Hassan', network: 'Tata Power', area: 'Hassan', district: 'Hassan', state: 'Karnataka', lat: 13.0072, lng: 76.0962, connectors: ['CCS2'], powerKw: 50, speed: 'fast', status: 'public', note: 'Junction for Chikmagalur / Sakleshpur.' },
  { id: 'has-sakles',  name: 'Sakleshpur Charging Point', network: 'Statiq', area: 'Sakleshpur', district: 'Hassan', state: 'Karnataka', lat: 12.9488, lng: 75.7982, connectors: ['Type2'], powerKw: 7.4, speed: 'standard', status: 'public' },
  { id: 'chk-statiq',  name: 'EV Charging Station - Chikmagalur', network: 'Statiq', area: 'Chikmagalur', district: 'Chikkamagaluru', state: 'Karnataka', lat: 13.3153, lng: 75.7762, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'public', note: '12+ chargers across town.' },

  // ─── KERALA - Kochi → Munnar / Wayanad ───────────────────────────────────────
  { id: 'idu-adimali', name: 'chargeMOD DC Fast - Adimali', network: 'chargeMOD', area: 'Adimali', district: 'Idukki', state: 'Kerala', lat: 10.0086, lng: 76.9560, connectors: ['CCS2'], powerKw: 60, speed: 'fast', status: 'public', note: 'Main stop on the Kochi-Munnar ghat.' },
  { id: 'idu-kseb',    name: 'KSEB Munnar DCFC', network: 'KSEB', area: 'Munnar', district: 'Idukki', state: 'Kerala', lat: 10.0889, lng: 77.0595, connectors: ['CCS2', 'CHAdeMO'], powerKw: 60, speed: 'fast', status: 'public', note: 'Works with chargeMOD & KeMapp apps.' },
  { id: 'idu-sihla',   name: 'Sihla Energy - Eastend Restaurant', network: 'Sihla Energy', area: 'Munnar', district: 'Idukki', state: 'Kerala', lat: 10.0905, lng: 77.0625, connectors: ['CCS2'], powerKw: 30, speed: 'fast', status: 'restaurant' },
  { id: 'idu-kumily',  name: 'chargeMOD - Kumily (Thekkady)', network: 'chargeMOD', area: 'Kumily', district: 'Idukki', state: 'Kerala', lat: 9.6037, lng: 77.1601, connectors: ['CCS2', 'Type2'], powerKw: 30, speed: 'fast', status: 'public' },
  { id: 'way-kalpetta',name: 'chargeMOD - Kalpetta', network: 'chargeMOD', area: 'Kalpetta', district: 'Wayanad', state: 'Kerala', lat: 11.6083, lng: 76.0820, connectors: ['CCS2'], powerKw: 60, speed: 'fast', status: 'public' },

  // ─── ANDHRA PRADESH ──────────────────────────────────────────────────────────
  { id: 'vsk-tata',    name: 'Tata Power Hub - Visakhapatnam', network: 'Tata Power', area: 'Visakhapatnam', district: 'Visakhapatnam', state: 'Andhra Pradesh', lat: 17.6868, lng: 83.2185, connectors: ['CCS2', 'CHAdeMO'], powerKw: 60, speed: 'fast', status: 'public', note: 'Base for the Araku Valley drive.' },
]

// ─── Links to live, always-current sources (no API, just URLs) ────────────────

/** Google Maps live search for "EV charging" within a district. Opens in a new tab. */
export function districtGoogleMapsUrl(d: DistrictEntry): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`EV charging stations in ${d.district}, ${d.state}`)}`
}

/** Government e-AMRIT national charging map (NITI Aayog). */
export const E_AMRIT_URL = 'https://e-amrit.niti.gov.in/charging-map'

/** Resolve a single curated station to a Google Maps place search. */
export function googleMapsUrl(s: EvStation): string {
  return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(`${s.name}, ${s.area}, ${s.district} EV charging`)}`
}

/** Directions to a station from the user's location. */
export function googleMapsDirectionsUrl(s: EvStation): string {
  return `https://www.google.com/maps/dir/?api=1&destination=${s.lat},${s.lng}`
}

export function stationsInDistrict(district: string): EvStation[] {
  return EV_STATIONS.filter((s) => s.district === district)
}

export const CONNECTOR_LABELS: Record<Connector, string> = {
  CCS2: 'CCS2',
  CHAdeMO: 'CHAdeMO',
  Type2: 'Type 2 AC',
  Bharat_DC: 'Bharat DC-001',
  Bharat_AC: 'Bharat AC-001',
}

export const STATUS_LABELS: Record<StationStatus, string> = {
  public: 'Public',
  guests_only: 'Guests only',
  hotel: 'At hotel',
  restaurant: 'At restaurant',
}
