// Stays (accommodation) layer - types, labels and OUTBOUND booking deep-links.
//
// Perch does NOT mirror Airbnb/OTA listings (no public API, scraping breaks their
// ToS + copyright, and the only "Airbnb APIs" are paid metered scrapers - exactly
// the surprise-billing risk we avoid). Instead:
//   1. Open-data stays from OpenStreetMap (keyless, $0) - generated into stays-osm.ts.
//   2. Community stays in Supabase (work-from-here WiFi/power ratings).
//   3. Legal deep-LINKS to each OTA's own search for a place (no data copied).
//
// Linking to a public search URL is fine; only re-hosting their listings is not.

export type StayType =
  | 'hotel' | 'homestay' | 'guest_house' | 'hostel' | 'apartment' | 'resort' | 'chalet' | 'motel'

// Open-data stay (OSM), generated by scripts/fetch-stays.ts.
export interface OsmStay {
  id: string
  name: string
  type: StayType
  area: string
  district: string
  state: string
  lat: number
  lng: number
  stars: number | null
  website: string | null
  phone: string | null
  hasInternet: boolean | null
  source: 'osm'
  nearestDestSlug: string
  distanceToDestKm: number
}

export const STAY_TYPE_LABELS: Record<StayType, string> = {
  hotel: 'Hotel',
  homestay: 'Homestay',
  guest_house: 'Guesthouse',
  hostel: 'Hostel',
  apartment: 'Apartment',
  resort: 'Resort',
  chalet: 'Cottage / chalet',
  motel: 'Motel',
}

export const STAY_TYPE_ICONS: Record<StayType, string> = {
  hotel: '🏨', homestay: '🏡', guest_house: '🏠', hostel: '🛏️',
  apartment: '🏢', resort: '🌴', chalet: '🛖', motel: '🚗',
}

export interface BookingLink {
  label: string
  url: string
  /** True if we earn affiliate revenue (or could) via this provider. */
  monetizable: boolean
}

/**
 * Legal outbound deep-links to each OTA's own search for a place. We send the
 * traveller to the provider's live, current inventory - we never copy it.
 * `place` should be a human query like "Ooty, Tamil Nadu".
 */
export function bookingSearchLinks(place: string): BookingLink[] {
  const q = encodeURIComponent(place)
  return [
    { label: 'Google Maps', url: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('stays in ' + place)}`, monetizable: false },
    { label: 'Airbnb', url: `https://www.airbnb.com/s/${q}/homes`, monetizable: false },
    { label: 'Booking.com', url: `https://www.booking.com/searchresults.html?ss=${q}`, monetizable: true },
    { label: 'Agoda', url: `https://www.agoda.com/search?text=${q}`, monetizable: true },
    { label: 'MakeMyTrip', url: `https://www.google.com/search?q=${encodeURIComponent(place + ' hotels')}+site%3Amakemytrip.com`, monetizable: true },
  ]
}

/** A coordinate maps link is reliable even when a stay has no good name. */
export function stayMapsLink(s: { lat: number; lng: number }): string {
  return `https://www.google.com/maps/search/?api=1&query=${s.lat},${s.lng}`
}
