// AUTO-GENERATED by scripts/fetch-wildlife-images.ts - do not edit by hand.
// Source: Wikimedia Commons (keyless MediaWiki API). Generated: 2026-06-29
// Real in-the-wild ANIMAL photos of each destination's headline species, scored
// toward wild/natural-habitat shots and away from zoos/cages/captivity, then
// downloaded + self-hosted under public/wildlife/ so next/image never hits
// Wikimedia at runtime. 23/23 resolved.
// CC-licensed; 'attribution' + 'license' + 'sourceUrl' credit authors.
// Re-run: npx tsx scripts/fetch-wildlife-images.ts

export interface WildlifeImage {
  url: string          // local path under public/wildlife/
  attribution: string  // author credit
  license: string      // CC license short name
  sourceUrl: string    // Wikimedia Commons file page
}

export const WILDLIFE_IMAGES: Record<string, WildlifeImage> = {
  "valparai": {
    "url": "/wildlife/valparai.jpg",
    "attribution": "Subhajit Saha",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:LTM_male_Valparai.jpg"
  },
  "megamalai": {
    "url": "/wildlife/megamalai.jpg",
    "attribution": "Thapalens",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Herd_of_wild_Asian_elephants_in_the_grasslands_of_Kaziranga.jpg"
  },
  "topslip": {
    "url": "/wildlife/topslip.jpg",
    "attribution": "Shiv's fotografia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_-_the_big_cat.jpg"
  },
  "mudumalai": {
    "url": "/wildlife/mudumalai.jpg",
    "attribution": "Shiv's fotografia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_-_the_big_cat.jpg"
  },
  "munnar": {
    "url": "/wildlife/munnar.jpg",
    "attribution": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nilgiri_tahr_(Nilgiritragus_hylocrius)_female.jpg"
  },
  "eravikulam": {
    "url": "/wildlife/eravikulam.jpg",
    "attribution": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Nilgiri_tahr_(Nilgiritragus_hylocrius)_female_head.jpg"
  },
  "thekkady": {
    "url": "/wildlife/thekkady.jpg",
    "attribution": "Megaurab09",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wild_Elephant_Herd_Walking_Across_Green_Open_Fields.jpg"
  },
  "gavi": {
    "url": "/wildlife/gavi.jpg",
    "attribution": "Soumendu Das",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lion_Tailed_Macaque_Macaca_Silenus_(106323697).jpeg"
  },
  "silent-valley": {
    "url": "/wildlife/silent-valley.jpg",
    "attribution": "Soumendu Das",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lion_Tailed_Macaque_Macaca_Silenus_(106323697).jpeg"
  },
  "wayanad": {
    "url": "/wildlife/wayanad.jpg",
    "attribution": "Megaurab09",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Wild_Elephant_Herd_Walking_Across_Green_Open_Fields.jpg"
  },
  "br-hills": {
    "url": "/wildlife/br-hills.jpg",
    "attribution": "Shiv's fotografia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_-_the_big_cat.jpg"
  },
  "kabini": {
    "url": "/wildlife/kabini.jpg",
    "attribution": "Davidvraju",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Black_Panther_-_India.jpg"
  },
  "kudremukh": {
    "url": "/wildlife/kudremukh.jpg",
    "attribution": "Soumendu Das",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Lion_Tailed_Macaque_Macaca_Silenus_(106323697).jpeg"
  },
  "nallamala": {
    "url": "/wildlife/nallamala.jpg",
    "attribution": "Shiv's fotografia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_-_the_big_cat.jpg"
  },
  "farahabad": {
    "url": "/wildlife/farahabad.jpg",
    "attribution": "Shiv's fotografia",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Panthera_tigris_-_the_big_cat.jpg"
  },
  "maredumilli": {
    "url": "/wildlife/maredumilli.jpg",
    "attribution": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leopard_(Panthera_pardus_pardus)_young_female_Kruger_2.jpg"
  },
  "coorg": {
    "url": "/wildlife/coorg.jpg",
    "attribution": "Yathin S Krishnappa",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Elephas_maximus_(Bandipur).jpg"
  },
  "srinagar": {
    "url": "/wildlife/srinagar.jpg",
    "attribution": "Tahirshawl",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:The_Last_Surviving_Population_of_Hangul.jpg"
  },
  "hemis": {
    "url": "/wildlife/hemis.jpg",
    "attribution": "Lee Elvin",
    "license": "CC BY-SA 3.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Snow_Leopard_(222234893).jpeg"
  },
  "tso-moriri": {
    "url": "/wildlife/tso-moriri.jpg",
    "attribution": "Chinchu2",
    "license": "CC BY-SA 2.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Chinchu2_Tibetan_Wild_Ass_at_Tso_Kar.jpg"
  },
  "tirthan-valley": {
    "url": "/wildlife/tirthan-valley.jpg",
    "attribution": "Megaurab09",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Himalayan_Tahr_at_Dawn.jpg"
  },
  "binsar": {
    "url": "/wildlife/binsar.jpg",
    "attribution": "Charles J. Sharp",
    "license": "CC BY-SA 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Leopard_(Panthera_pardus_pardus)_young_female_Kruger_2.jpg"
  },
  "valley-of-flowers": {
    "url": "/wildlife/valley-of-flowers.jpg",
    "attribution": "Dibyendu Ash",
    "license": "CC BY 4.0",
    "sourceUrl": "https://commons.wikimedia.org/wiki/File:Bharal_Female_from_North_Sikkim_India_16.10.2019.jpg"
  }
}

export function wildlifeImage(slug: string): WildlifeImage | undefined {
  return WILDLIFE_IMAGES[slug]
}
