-- AUTO-GENERATED from lib/data/destinations.ts (npx tsx scripts/gen-dest-sql.ts).
-- Seeds every catalogue destination so community data (WiFi, work spots,
-- journeys) and the contribution form can attach by slug. Safe to re-run.

CREATE EXTENSION IF NOT EXISTS postgis;

ALTER TABLE destinations ADD COLUMN IF NOT EXISTS
  category TEXT DEFAULT 'hill_station'
  CHECK (category IN ('hill_station', 'coastal', 'city', 'forest', 'heritage', 'gateway'));

INSERT INTO destinations (name, slug, state, elevation_m, category, climate_notes, location) VALUES
  ('Ooty (Udhagamandalam)', 'ooty', 'Tamil Nadu', 2240, 'hill_station', 'The best known hill station in the south, the "Queen of the Nilgiris", with botanical gardens, a toy train and colonial charm.', ST_Point(76.695, 11.4102)::geography),
  ('Coonoor', 'coonoor', 'Tamil Nadu', 1858, 'hill_station', 'Quieter and milder than Ooty, set among tea estates with Sims Park and viewpoints over the plains.', ST_Point(76.7959, 11.353)::geography),
  ('Kotagiri', 'kotagiri', 'Tamil Nadu', 1793, 'hill_station', 'The oldest and least crowded of the three Nilgiri towns, with a mild climate and clean air.', ST_Point(76.8606, 11.4216)::geography),
  ('Kodaikanal', 'kodaikanal', 'Tamil Nadu', 2133, 'hill_station', 'The "Princess of Hill Stations" in the Palani Hills, built around a star-shaped lake amid shola forest.', ST_Point(77.4892, 10.2381)::geography),
  ('Yercaud', 'yercaud', 'Tamil Nadu', 1515, 'hill_station', 'An affordable, low-key hill station in the Shevaroys, 35 km from Salem, with coffee and orange groves.', ST_Point(78.209, 11.7799)::geography),
  ('Valparai', 'valparai', 'Tamil Nadu', 1193, 'hill_station', 'A remote tea-estate plateau reached by a 40-hairpin ghat, rich in wildlife and very quiet.', ST_Point(76.955, 10.327)::geography),
  ('Yelagiri', 'yelagiri', 'Tamil Nadu', 1110, 'hill_station', 'A compact weekend hill station within easy reach of Bengaluru and Chennai, good for a quiet retreat.', ST_Point(78.639, 12.5817)::geography),
  ('Kolli Hills', 'kolli-hills', 'Tamil Nadu', 1300, 'hill_station', 'An offbeat Eastern Ghats range famous for its 70-hairpin road, waterfalls and herbal farms.', ST_Point(78.338, 11.25)::geography),
  ('Megamalai', 'megamalai', 'Tamil Nadu', 1500, 'hill_station', 'The "High Wavy Mountains", a pristine high-range cardamom and tea country, largely undeveloped.', ST_Point(77.4, 9.63)::geography),
  ('Topslip', 'topslip', 'Tamil Nadu', 800, 'forest', 'A forest base inside the Anamalai Tiger Reserve, known for trekking and elephant herds.', ST_Point(76.824, 10.436)::geography),
  ('Sirumalai', 'sirumalai', 'Tamil Nadu', 1600, 'hill_station', 'A small hill range near Dindigul known for its native banana variety and cool forested slopes.', ST_Point(77.98, 10.28)::geography),
  ('Javadi Hills', 'javadi-hills', 'Tamil Nadu', 1100, 'hill_station', 'An extensive, tribal Eastern Ghats range with sandalwood forests and a slow pace of life.', ST_Point(78.75, 12.55)::geography),
  ('Kalrayan Hills', 'kalrayan-hills', 'Tamil Nadu', 1000, 'hill_station', 'A pair of tribal hill ranges between Salem and Villupuram, with waterfalls and terraced farms.', ST_Point(78.6, 11.7)::geography),
  ('Pachamalai', 'pachamalai', 'Tamil Nadu', 1000, 'hill_station', 'A green Eastern Ghats range near Trichy with springs, waterfalls and tribal hamlets.', ST_Point(78.45, 11.35)::geography),
  ('Gudalur', 'gudalur', 'Tamil Nadu', 1100, 'gateway', 'A green junction town between the Nilgiris, Wayanad and Mysuru, surrounded by tea and forest.', ST_Point(76.491, 11.501)::geography),
  ('Mudumalai', 'mudumalai', 'Tamil Nadu', 1140, 'forest', 'A tiger reserve at the tri-junction of Tamil Nadu, Karnataka and Kerala, rich in elephants and gaur.', ST_Point(76.54, 11.57)::geography),
  ('Munnar', 'munnar', 'Kerala', 1600, 'hill_station', 'Kerala''s flagship hill station, an expanse of rolling tea estates in the high ranges of Idukki.', ST_Point(77.0595, 10.0889)::geography),
  ('Wayanad (Kalpetta)', 'wayanad', 'Kerala', 780, 'hill_station', 'A plateau district of spice and coffee estates, caves and waterfalls, increasingly popular with nomads.', ST_Point(76.082, 11.6083)::geography),
  ('Vythiri', 'vythiri', 'Kerala', 700, 'forest', 'Wayanad''s resort belt, full of tree-houses and rainforest eco-lodges near the Lakkidi ghat.', ST_Point(76.04, 11.55)::geography),
  ('Thekkady (Kumily)', 'thekkady', 'Kerala', 900, 'forest', 'The gateway to Periyar Tiger Reserve, set in spice plantations on the Kerala-Tamil Nadu border.', ST_Point(77.1601, 9.6037)::geography),
  ('Vagamon', 'vagamon', 'Kerala', 1100, 'hill_station', 'Rolling green meadows and pine forests on the Kottayam-Idukki border, quieter than Munnar.', ST_Point(76.9, 9.685)::geography),
  ('Ponmudi', 'ponmudi', 'Kerala', 1100, 'hill_station', 'A misty hill station just 60 km from Thiruvananthapuram, with hairpin roads and shola forest.', ST_Point(77.12, 8.76)::geography),
  ('Nelliyampathy', 'nelliyampathy', 'Kerala', 1500, 'hill_station', 'A quiet range of orange, cardamom and coffee plantations reached by a scenic ghat from Palakkad.', ST_Point(76.696, 10.535)::geography),
  ('Peermade', 'peermade', 'Kerala', 915, 'hill_station', 'A plantation hill town on the road to Thekkady, with tea, coffee, cardamom and rubber estates.', ST_Point(76.98, 9.574)::geography),
  ('Devikulam', 'devikulam', 'Kerala', 1800, 'hill_station', 'A high, serene hill town near Munnar centred on the Sita Devi lake, with mineral springs.', ST_Point(77.1, 10.05)::geography),
  ('Marayoor', 'marayoor', 'Kerala', 1000, 'hill_station', 'Famous for natural sandalwood forests, sugarcane jaggery and dolmens, north of Munnar.', ST_Point(77.162, 10.277)::geography),
  ('Lakkidi', 'lakkidi', 'Kerala', 700, 'gateway', 'The misty gateway to Wayanad at the top of the Thamarassery ghat, one of the wettest spots in the south.', ST_Point(76.03, 11.53)::geography),
  ('Ramakkalmedu', 'ramakkalmedu', 'Kerala', 1100, 'hill_station', 'A windswept ridge near Thekkady with sweeping views over the Tamil Nadu plains and strong breezes.', ST_Point(77.15, 9.69)::geography),
  ('Gavi', 'gavi', 'Kerala', 1000, 'forest', 'An eco-tourism forest village inside the Periyar belt, known for birding and guided treks.', ST_Point(77.16, 9.44)::geography),
  ('Silent Valley (Mukkali)', 'silent-valley', 'Kerala', 1000, 'forest', 'One of India''s last untouched tropical rainforests, accessed from Mukkali in Palakkad.', ST_Point(76.44, 11.09)::geography),
  ('Eravikulam (Anamudi)', 'eravikulam', 'Kerala', 2000, 'forest', 'A high-altitude national park above Munnar, home to the Nilgiri tahr and Anamudi, the highest peak in the south.', ST_Point(77.05, 10.19)::geography),
  ('Coorg (Madikeri)', 'coorg', 'Karnataka', 1525, 'hill_station', 'The "Scotland of India", coffee-plantation country with planters'' bungalows, waterfalls and a slow pace.', ST_Point(75.7382, 12.4244)::geography),
  ('Chikmagalur', 'chikmagalur', 'Karnataka', 1090, 'hill_station', 'The birthplace of Indian coffee, ringed by the Baba Budan range and Mullayanagiri, the state''s highest peak.', ST_Point(75.772, 13.3161)::geography),
  ('Sakleshpur', 'sakleshpur', 'Karnataka', 949, 'hill_station', 'Green hills and spice estates under three hours from Bengaluru, quieter than Coorg.', ST_Point(75.785, 12.943)::geography),
  ('Kemmanagundi', 'kemmanagundi', 'Karnataka', 1434, 'hill_station', 'A garden hill station in the Baba Budan range with waterfalls, rock gardens and sunset points.', ST_Point(75.76, 13.55)::geography),
  ('Nandi Hills', 'nandi-hills', 'Karnataka', 1478, 'hill_station', 'A historic fortified hill 60 km from Bengaluru, famous for sunrise above a sea of clouds.', ST_Point(77.683, 13.37)::geography),
  ('Kudremukh', 'kudremukh', 'Karnataka', 1894, 'forest', 'A "horse-face" peak and national park of shola-grassland, one of the best treks in the south.', ST_Point(75.262, 13.224)::geography),
  ('Agumbe', 'agumbe', 'Karnataka', 643, 'forest', 'The "Cherrapunji of the South", a rainforest village famous for sunsets and king cobra research.', ST_Point(75.094, 13.503)::geography),
  ('BR Hills', 'br-hills', 'Karnataka', 1100, 'forest', 'The Biligirirangana Hills, a tribal forest reserve linking the Western and Eastern Ghats.', ST_Point(77.15, 11.97)::geography),
  ('Mullayanagiri', 'mullayanagiri', 'Karnataka', 1930, 'hill_station', 'The highest peak in Karnataka, a popular trek and drive above Chikmagalur with cloud views.', ST_Point(75.719, 13.392)::geography),
  ('Baba Budangiri', 'baba-budangiri', 'Karnataka', 1895, 'hill_station', 'A sacred range above Chikmagalur where coffee was first grown in India, with caves and peaks.', ST_Point(75.76, 13.43)::geography),
  ('Kodachadri', 'kodachadri', 'Karnataka', 1343, 'forest', 'A dense Western Ghats peak near Kollur, a classic jeep-and-trek destination above the clouds.', ST_Point(74.87, 13.86)::geography),
  ('Kabini', 'kabini', 'Karnataka', 780, 'forest', 'A famous wildlife destination on the Kabini backwaters at the edge of Nagarhole National Park.', ST_Point(76.35, 11.97)::geography),
  ('Devarayanadurga', 'devarayanadurga', 'Karnataka', 1200, 'hill_station', 'A rocky, temple-topped hill near Tumakuru, an easy forested escape from Bengaluru.', ST_Point(77.22, 13.37)::geography),
  ('Skandagiri', 'skandagiri', 'Karnataka', 1450, 'hill_station', 'A night-trek favourite near Nandi Hills, climbed for dawn above the clouds.', ST_Point(77.68, 13.51)::geography),
  ('Charmadi Ghat', 'charmadi', 'Karnataka', 1000, 'gateway', 'A lush, winding ghat linking the coast to Chikmagalur, full of waterfalls and viewpoints.', ST_Point(75.48, 13.03)::geography),
  ('Mandalpatti', 'mandalpatti', 'Karnataka', 1600, 'hill_station', 'A high viewpoint near Madikeri reached by jeep, famous for sunrise over a sea of mist.', ST_Point(75.62, 12.36)::geography),
  ('Savandurga', 'savandurga', 'Karnataka', 1226, 'hill_station', 'One of Asia''s largest monolith hills, a day-trip climb and trekking spot near Bengaluru.', ST_Point(77.296, 12.918)::geography),
  ('Araku Valley', 'araku-valley', 'Andhra Pradesh', 1300, 'hill_station', 'The "Ooty of Andhra", a coffee-growing tribal valley reached by one of India''s most scenic train rides.', ST_Point(82.874, 18.3271)::geography),
  ('Horsley Hills', 'horsley-hills', 'Andhra Pradesh', 1265, 'hill_station', 'A small, calm hill station near the Karnataka border, the "Ooty of Andhra Pradesh" for the south of the state.', ST_Point(78.403, 13.659)::geography),
  ('Lambasingi', 'lambasingi', 'Andhra Pradesh', 1025, 'hill_station', 'The "Kashmir of Andhra", a tribal village that drops near freezing in winter, rare for the south.', ST_Point(82.49, 17.8)::geography),
  ('Maredumilli', 'maredumilli', 'Andhra Pradesh', 900, 'forest', 'A dense evergreen forest area with waterfalls and tribal eco-camps, east of the Godavari.', ST_Point(81.73, 17.53)::geography),
  ('Nallamala Hills (Srisailam)', 'nallamala', 'Andhra Pradesh', 1100, 'forest', 'A vast tiger-reserve range along the Krishna gorge, centred on the Srisailam pilgrimage town.', ST_Point(78.868, 16.073)::geography),
  ('Ananthagiri Hills', 'ananthagiri', 'Telangana', 700, 'hill_station', 'A forested hill range 90 km from Hyderabad with coffee trails, the source of the Musi river.', ST_Point(78, 17.55)::geography),
  ('Farahabad (Amrabad)', 'farahabad', 'Telangana', 850, 'forest', 'A viewpoint deep in the Amrabad Tiger Reserve, overlooking the Nallamala forest and Krishna valley.', ST_Point(78.95, 16.24)::geography),
  ('Puducherry', 'puducherry', 'Puducherry', 5, 'coastal', 'Not a hill station but a top southern remote-work base: French-quarter cafes, beaches and a real coworking scene.', ST_Point(79.8083, 11.9416)::geography)
ON CONFLICT (slug) DO UPDATE SET
  name         = EXCLUDED.name,
  state        = EXCLUDED.state,
  elevation_m  = EXCLUDED.elevation_m,
  category     = EXCLUDED.category,
  climate_notes = EXCLUDED.climate_notes,
  location     = EXCLUDED.location;
